---
apiVersion: stagetime.sthings.tiab.ssc.sva.de/v1beta1
kind: RevisionRun
metadata:
  labels:
    app.kubernetes.io/name: revisionrun
    app.kubernetes.io/instance: revisionrun-simulation
    app.kubernetes.io/part-of: stagetime-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: stagetime-operator
  name: revisionrun-simulation
spec:
  repository: stuttgart-things
  # revision: ad31212465653
  technologies:
    # - id: docker1
    #   kind: docker
    #   path: ./Dockerfile
    #   canfail: false
    #   stage: 0
    #   resolver: revision=tagged; pathInRepo=this
    - id: test0
      kind: simulation
      resolver: revision=main
      params: scriptTimeout=10s
      canfail: false
    - id: test1
      kind: simulation
      resolver: revision=main
      params: scriptTimeout=25s
      canfail: true
    # - id: test2
    #   kind: simulation
    # #   stage: 0
    #   resolver: revision=main;
    #   params: scriptTimeout=15s;
    #   canfail: true