---
apiVersion: stagetime.sthings.tiab.ssc.sva.de/v1beta1
kind: RevisionRun
metadata:
  labels:
    app.kubernetes.io/name: revisionrun
    app.kubernetes.io/instance: revisionrun-sample
    app.kubernetes.io/part-of: stagetime-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: stagetime-operator
  name: revisionrun-sample
spec:
  repository: stuttgart-things
  technologies:
    - id: docker1
      kind: docker
      path: ./Dockerfile
      canfail: false
      stage: 0
      resolver: revision=tagged; pathInRepo=this
    - id: test
      kind: simulation
      resolver: revision=tagged;
      params: scriptTimeout=10s;
      canfail: false
